In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')

### EDA

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [4]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
5045,913,24,Male,Hoodie,Clothing,56.0,Arkansas,M,Green,Winter,3.4,Yes,Next Day Air,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31.0,Debit Card,Weekly
5047,3572,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5.0,Bank Transfer,Every 3 Months

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [6]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [7]:
rows,cols = df.shape
print(f"Total Number of Rows : {rows}")
print(f"Total Number of Columns : {cols}")

Total Number of Rows : 5050
Total Number of Columns : 17

In [8]:
# df.isnull().any()
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

### DATA CLEANING

In [9]:
df['Item Purchased'].unique()

array(['T-shirt', 'Sunglasses', 'Shirt', 'Gloves', 'Jewelry', 'Shorts',
       'Hat', 'Handbag', 'Shoes', 'Coat', 'Laptop', 'Hoodie', 'Phone',
       'Jacket', 'Pants', 'Backpack', 'Socks', 'Jeans', 'Bag', 'Belt',
       'Watch', 'Headphones', 'Blouse', 'Sandals', 'Skirt', 'Sweater',
       'Scarf', 'Sneakers', 'Boots', 'Dress'], dtype=object)

In [10]:
df['Category'].unique()

array(['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear'],
      dtype=object)

In [11]:
df.groupby(by='Category')['Item Purchased'].nunique()

Category
Accessories    15
Clothing       17
Electronics     7
Footwear        4
Outerwear       2
Name: Item Purchased, dtype: int64

In [12]:
df.groupby(by='Category')['Item Purchased'].unique()

Category
Accessories    [Sunglasses, Gloves, Jewelry, Hat, Handbag, Ph...
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone,...
Electronics    [Laptop, Phone, Watch, Bag, Shoes, Shirt, Head...
Footwear                       [Shoes, Sandals, Sneakers, Boots]
Outerwear                                         [Coat, Jacket]
Name: Item Purchased, dtype: object

In [13]:
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_column',None)
pd.set_option('display.max_row',None)

In [14]:
df.groupby(by='Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [15]:
correct_mapping = {
    # Clothing
    'T-shirt':'Clothing', 'Shirt':'Clothing', 'Hoodie':'Clothing', 'Pants':'Clothing',
    'Jeans':'Clothing', 'Blouse':'Clothing', 'Skirt':'Clothing', 'Sweater':'Clothing',
    'Dress':'Clothing', 'Shorts':'Clothing', 'Socks':'Clothing',

    # Accessories
    'Sunglasses':'Accessories', 'Gloves':'Accessories', 'Jewelry':'Accessories', 'Hat':'Accessories',
    'Handbag':'Accessories', 'Backpack':'Accessories', 'Belt':'Accessories', 'Bag':'Accessories',
    'Scarf':'Accessories', 

    # Electronics
    'Laptop':'Electronics', 'Phone':'Electronics', 'Watch':'Electronics', 'Headphones':'Electronics',

    # Footwear
    'Shoes':'Footwear', 'Sandals':'Footwear', 'Sneakers':'Footwear', 'Boots':'Footwear',

    # Outerwear
    'Coat':'Outerwear', 'Jacket':'Outerwear'
}

df['Category'] = df['Item Purchased'].map(correct_mapping)

In [16]:
df.groupby(by='Category')['Item Purchased'].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [17]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

### Handling with Null Values

#### Purchase Amount (USD)

In [18]:
# Fill the null value to the mean of their Purechase Amount (USD) according to Item Purchased
df['Purchase Amount (USD)'] = df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean'))

In [19]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

#### Size

In [20]:
df['Size'].unique()

array(['XL', 'M', 'L', 'S', nan], dtype=object)

In [21]:
df['Size'].value_counts()

Size
M     1981
L     1282
S      874
XL     543
Name: count, dtype: int64

In [22]:
df.groupby(by=['Category','Item Purchased'])['Size'].unique()

Category     Item Purchased
Accessories  Backpack               [M, S, L, XL]
             Bag               [M, L, nan, XL, S]
             Belt                   [M, S, XL, L]
             Gloves                 [L, M, S, XL]
             Handbag                [S, XL, M, L]
             Hat                    [M, L, S, XL]
             Jewelry                [L, XL, M, S]
             Scarf                  [M, L, S, XL]
             Sunglasses             [M, L, S, XL]
Clothing     Blouse                 [M, L, S, XL]
             Dress                  [XL, M, L, S]
             Hoodie                 [M, L, S, XL]
             Jeans                  [L, M, XL, S]
             Pants                  [L, M, XL, S]
             Shirt             [M, XL, L, S, nan]
             Shorts                 [S, M, L, XL]
             Skirt                  [S, L, M, XL]
             Socks                  [M, XL, L, S]
             Sweater                [M, S, L, XL]
             T-shirt                [XL, M, S, L]
Electronics  Headphones        [S, M, nan, L, XL]
             Laptop            [nan, M, S, XL, L]
             Phone             [nan, L, S, M, XL]
             Watch             [nan, M, L, XL, S]
Footwear     Boots                  [L, M, XL, S]
             Sandals                [M, S, L, XL]
             Shoes             [M, L, nan, XL, S]
             Sneakers               [S, M, L, XL]
Outerwear    Coat                   [XL, M, S, L]
             Jacket                 [L, S, M, XL]
Name: Size, dtype: object

In [23]:
# Replacing all values and null value of 'Electronics' Category with 'Not Applicable'
df.loc[df['Category']=='Electronics','Size'] = 'Not Applicable'

In [24]:
df.groupby(by='Category')['Size'].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [25]:
# Replacing all value and null values of 'Accessories' Category with 'Free Size'
df.loc[df['Category']=='Accessories','Size'] = 'Free Size'

In [26]:
df.groupby(by='Category')['Size'].unique()

Category
Accessories           [Free Size]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [27]:
# Replace all value and null values of 'Footwear' Category with 'Not Available'
df.loc[df['Category']=='Footwear','Size'] = 'Not Available'

In [28]:
df.groupby(by='Category')['Size'].unique()

Category
Accessories           [Free Size]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear          [Not Available]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [29]:
# Replacing null values of 'Clothong' Category with Mode values
df.loc[(df['Category']=='Clothing') & (df['Size'].isnull()),'Size'] = df[df['Category']=='Clothing']['Size'].mode()[0]

In [30]:
df.groupby(by='Category')['Size'].unique()

Category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear        [Not Available]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

In [31]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [32]:
df['Review Rating'].unique()

array([3.2, 3.9, 3.1, 4.2, 3.6, 3.4, nan, 4. , 4.3, 2.8, 4.8, 3.8, 3.3,
       2.5, 3. , 4.5, 2.6, 2.9, 4.1, 4.6, 4.7, 3.5, 4.9, 5. , 4.4, 1. ,
       2.7, 2. , 3.7])

In [33]:
df.groupby('Item Purchased')['Review Rating'].mean()

Item Purchased
Backpack      3.758333
Bag           3.168539
Belt          3.762963
Blouse        3.677647
Boots         3.813194
Coat          3.721875
Dress         3.750000
Gloves        3.862774
Handbag       3.771975
Hat           3.796753
Headphones    3.075949
Hoodie        3.716779
Jacket        3.761446
Jeans         3.651969
Jewelry       3.761850
Laptop        3.191176
Pants         3.720833
Phone         2.939024
Sandals       3.837037
Scarf         3.702564
Shirt         3.427273
Shoes         3.546154
Shorts        3.722981
Skirt         3.779747
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.745679
Sweater       3.768712
T-shirt       3.790541
Watch         3.100000
Name: Review Rating, dtype: float64

In [34]:
# Fill null values of 'Review Rating' with the mean of each 'Item Purchased'
df['Review Rating'] = df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'].transform('mean'))

In [35]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

#### Previous Purchases

In [36]:
# Fill the Null value to 0 of 'Previous Purchases'
df['Previous Purchases'] = df['Previous Purchases'].fillna(0)

In [37]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

### Checking Deplicates

In [38]:
# df.duplicated().any()
df.duplicated().sum()

np.int64(50)

In [39]:
len(df)

5050

In [40]:
df.drop_duplicates(inplace = True)

In [41]:
df.duplicated().any()
# df.duplicated().sum()

np.False_

In [42]:
len(df)

5000

### Renaming the Columns Name

In [43]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [44]:
# Replace space in column name to '_' and make column name to lower-case
df.columns = df.columns.str.replace(' ','_').str.lower()

In [45]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [46]:
# Rename the column from 'purchase_amount_(USD)' to 'purchase_amount'
df.rename(columns={'purchase_amount_(usd)':'purchase_amount'},inplace=True)

In [47]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [48]:
df.sample(20)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
4820,1021,24,Male,Scarf,Accessories,95.000000,Delaware,Free Size,Black,Fall,4.5,Yes,Express,Yes,41.0,Debit Card,Annually
1041,4928,62,Other,Watch,Electronics,685.231471,Houston,Not Applicable,White,Summer,3.1,Yes,Standard,No,4.0,Credit Card,Weekly
1432,2606,41,Male,Hoodie,Clothing,93.000000,Nevada,M,White,Spring,3.7,No,2-Day Shipping,No,32.0,Venmo,Fortnightly
3617,3895,66,Female,Skirt,Clothing,78.000000,Connecticut,L,White,Spring,3.9,No,2-Day Shipping,No,44.0,Credit Card,Every 3 Months
2861,4839,43,Male,Bag,Accessories,1063.290000,Houston,Free Size,White,Autumn,3.0,Yes,Standard,Yes,30.0,PayPal,Quarterly
4243,52,59,Male,Skirt,Clothing,59.000000,Vermont,XL,Gray,Winter,4.7,Yes,2-Day Shipping,Yes,7.0,Credit Card,Quarterly
3294,37,35,Male,T-shirt,Clothing,69.000000,Illinois,M,Maroon,Winter,4.6,Yes,Free Shipping,Yes,44.0,PayPal,Fortnightly
2172,1400,19,Male,Hat,Accessories,81.000000,Nebraska,Free Size,Olive,Winter,3.1,No,Store Pickup,Yes,48.0,Venmo,Annually
4655,577,48,Male,Hat,Accessories,68.000000,Washington,Free Size,Black,Winter,5.0,Yes,2-Day Shipping,Yes,5.0,Credit Card,Every 3 Months
4069,1325,39,Male,Jewelry,Accessories,77.000000,Indiana,Free Size,Orange,Summer,3.8,No,Free Shipping,Yes,11.0,Credit Card,Fortnightly
871,3056,27,Female,Sandals,Footwear,22.000000,Kansas,Not Available,Violet,Fall,5.0,No,Standard,No,5.0,Debit Card,Bi-Weekly
1029,5012,33,Other,Laptop,Electronics,509.470000,Los Angeles,Not Applicable,Green,Spring,4.0,No,Express,No,11.0,Debit Card,Weekly
1204,62,55,Male,Scarf,Accessories,68.000000,Texas,Free Size,Orange,Winter,4.7,Yes,Store Pickup,Yes,21.0,Credit Card,Every 3 Months
2048,2521,64,Male,Jacket,Outerwear,56.000000,Illinois,L,Magenta,Summer,3.1,No,Next Day Air,No,16.0,Cash,Every 3 Months
971,2294,37,Male,Sweater,Clothing,68.000000,Georgia,L,Green,Fall,3.3,No,Express,No,16.0,Debit Card,Every 3 Months
4367,2554,69,Male,Jewelry,Accessories,25.000000,Vermont,Free Size,Maroon,Summer,4.5,No,Store Pickup,No,28.0,Venmo,Every 3 Months
4577,2863,68,Female,Coat,Outerwear,75.000000,Hawaii,S,Violet,Summer,4.7,No,Store Pickup,No,5.0,Bank Transfer,Every 3 Months
2053,737,18,Male,Dress,Clothing,58.000000,Colorado,L,Maroon,Spring,2.9,Yes,2-Day Shipping,Yes,32.0,Credit Card,Every 3 Months
4036,719,22,Male,Shirt,Clothing,22.000000,Florida,M,Peach,Summer,4.6,Yes,Standard,Yes,25.0,Bank Transfer,Annually
3628,3788,37,Female,Blouse,Clothing,80.000000,New York,M,Pink,Fall,3.6,No,2-Day Shipping,No,46.0,PayPal,Every 3 Months

### Connecting to PostgreSQL

In [52]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus # this because my password has '@'
username = 'postgres'
password = quote_plus('R0h@n.Postgre')
host = 'localhost'
port = '5432'
database = 'customer_shopping_behavior_2'
# Step-1 Connect to the PostgreSQL
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step-2 Load DataFrame into PostgreSQl
table_name = 'customer'
df.to_sql(table_name,engine,if_exists='replace',index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_shopping_behavior_2'.